name: news_app
version: 1.0.0+1
publish_to: none
description: News APP.
environment: 
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  get: 4.6.5
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  carousel_slider: ^4.2.1
  cached_network_image: 3.2.3
  animated_splash_screen: ^1.3.0
  page_transition: ^2.0.9
  flutter_spinkit: 5.1.0
  shared_preferences: ^2.0.17
  shimmer: 2.0.0
  google_fonts: 4.0.3
  badges: ^3.0.2
  flutter_html: ^3.0.0-alpha.3
  url_launcher: 6.1.10
  intl: 0.18.0
  flutter_bcrypt: 1.0.8
  flutter_share: 2.0.0
  modal_progress_hud_nsn: 0.3.0
  webview_flutter: 4.0.7
  infinite_scroll_pagination: 3.2.0
  flutter_typeahead: 4.3.7
  flutter:
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/assets/
    - assets/assets/splash_screen.svg

